import { createApp } from 'vue'
import App from './App.vue'
import router from './router';
// require('@/assets/js/vendor/bootstrap/css/bootstrap.min.css')
// require('@/assets/fonts/fontawesome/css/all.min.css')
// require('@/assets/js/plugins/fancybox/css/jquery.fancybox.min.css')
// require('@/assets/js/plugins/mediaelementplayer/css/mediaelementplayer.min.css')
// require('@/assets/js/plugins/twenty-twenty/css/twentytwenty.min.css')
// require('@/assets/js/plugins/owl-carousel/assets/owl.carousel.min.css')
// require('@/assets/js/plugins/owl-carousel/assets/owl.theme.default.min.css')
// require('@/assets/css/social-networks/social-networks.min.css')
// require('@/assets/css/animate/animate.min.css')
// require('@/assets/css/style.css')
// require('@/assets/css/custom.css')
//require('@/')
// require('@/assets/images/favicon/favicon-32x32.png')
// require('@/assets/images/favicon/favicon-192x192.png')
// require('@/assets/images/favicon/favicon-180x180.png')
// require('@/assets/images/favicon/favicon-270x270.png')
// require('@/assets/images/shop/005-42x67.jpg')

//require('@/assets/js/vendor/jquery/jquery-3.6.0.min.js')
//require('@/assets/js/vendor/jquery/jquery-ui.min.js')
//require('@/assets/js/vendor/bootstrap/js/bootstrap.bundle.min.js')
//require('@/assets/js/plugins/animsition/js/animsition.min.js')
//require('@/assets/js/plugins/appear/jquery.appear.min.js')
//require('@/assets/js/plugins/countto/jquery.countTo.min.js')
//require('@/assets/js/plugins/downcount/jquery.downCount.min.js')
//require('@/assets/js/plugins/easy-pie-chart/jquery.easypiechart.min.js')
//require('@/assets/js/plugins/fancybox/js/jquery.fancybox.min.js')
//require('@/assets/js/plugins/fitvids/jquery.fitvids.min.js')
// require('@/assets/js/plugins/isotope/isotope.pkgd.min.js')
// require('@/assets/js/plugins/mediaelementplayer/js/mediaelement-and-player.min.js')
// require('@/assets/js/plugins/owl-carousel/owl.carousel.min.js')
// require('@/assets/js/plugins/pace/pace.min.js')
// require('@/assets/js/plugins/parallax/jquery.parallax-1.1.3.min.js')
// require('@/assets/js/plugins/perfect-scrollbar/perfect-scrollbar.jquery.min.js')
// require('@/assets/js/plugins/sticky-sidebar/jquery.sticky-sidebar.min.js')
// require('@/assets/js/plugins/tweetie/tweetie.min.js')
// require('@/assets/js/plugins/twenty-twenty/js/twentytwenty.min.js')
// require('@/assets/js/plugins/typed/typed.min.js')
// //require('@/assets/js/plugins/validation/jquery.validate.min.js')
// require('@/assets/js/scripts.js')


createApp(App).use(router).mount('#app')
